imports:
  - { resource: src/Command/services.yaml }
  - { resource: src/Config/services.yaml }
  - { resource: src/DatabaseConfig/services.yaml }
  - { resource: src/Module/services.yaml }
  - { resource: src/ProductImage/services.yaml }
  - { resource: src/Template/services.yaml }
  - { resource: src/DatabaseSchema/services.yaml }
  - { resource: src/ThemeMetadata/services.yaml }
  - { resource: src/ThemeSettings/services.yaml }
  - { resource: src/ThemeTemplate/services.yaml }