imports:
  - { resource: src/Command/services.yaml }
  - { resource: src/Config/services.yaml }
  - { resource: src/DatabaseConfig/services.yaml }
  - { resource: src/Module/services.yaml }
  - { resource: src/Template/services.yaml }