services:
  _defaults:
    autowire: true
    public: false

  oxid_esales.oxid_eshop_update_component.command.decoder_command:
    class: OxidEsales\OxidEshopUpdateComponent\ConfigDecoder\Command\DecoderCommand
    tags:
      - { name: 'console.command' }

  oxid_esales.oxid_eshop_update_component.symfony_console_output:
    class: Symfony\Component\Console\Output\ConsoleOutput
