services:
  _defaults:
    autowire: true
    public: false

  oxid_esales.oxid_eshop_update_component.command.configuration_decoding_command:
    class: OxidEsales\OxidEshopUpdateComponent\Decoder\Command\ConfigurationDecodingCommand
    arguments:
      - '@oxid_esales.oxid_eshop_update_component.configuration_decoder'
    tags:
      - { name: 'console.command' }

  oxid_esales.oxid_eshop_update_component.configuration_decoder:
    class: OxidEsales\OxidEshopUpdateComponent\Decoder\Service\ConfigurationDecoder

  OxidEsales\OxidEshopUpdateComponent\Decoder\DataMigration\ConfigurationInterface:
    class: OxidEsales\OxidEshopUpdateComponent\Decoder\DataMigration\Configuration

  oxid_esales.oxid_eshop_update_component.command.user_payment_decoding_command:
    class: OxidEsales\OxidEshopUpdateComponent\Decoder\Command\UserPaymentsDecodingCommand
    arguments:
      - '@oxid_esales.oxid_eshop_update_component.user_payments_decoder'
    tags:
      - { name: 'console.command' }

  oxid_esales.oxid_eshop_update_component.user_payments_decoder:
    class: OxidEsales\OxidEshopUpdateComponent\Decoder\Service\UserPaymentsDecoder

  OxidEsales\OxidEshopUpdateComponent\Decoder\DataMigration\UserPaymentInterface:
    class: OxidEsales\OxidEshopUpdateComponent\Decoder\DataMigration\UserPayment

  OxidEsales\OxidEshopUpdateComponent\Decoder\DataMigration\ValidatorInterface:
    class: OxidEsales\OxidEshopUpdateComponent\Decoder\DataMigration\Validator

  oxid_esales.oxid_eshop_update_component.symfony_console_output:
    class: Symfony\Component\Console\Output\ConsoleOutput

  OxidEsales\OxidEshopUpdateComponent\Adapter\ShopAdapterInterface:
    class: OxidEsales\OxidEshopUpdateComponent\Adapter\ShopAdapter
