services:
  _defaults:
    autowire: true
    public: false

  oxid_esales.oxid_eshop_update_component.command.install_all_modules_configuration_command:
    class: OxidEsales\OxidEshopUpdateComponent\Module\Command\InstallAllModulesConfigurationCommand
    tags:
      - { name: 'console.command' }

  OxidEsales\OxidEshopUpdateComponent\Module\Command\TransferModuleDataToProjectConfigurationCommand:
    class: OxidEsales\OxidEshopUpdateComponent\Module\Command\TransferModuleDataToProjectConfigurationCommand
    tags:
      - { name: 'console.command' }

  OxidEsales\OxidEshopUpdateComponent\Module\Service\ModuleSettingsTransferringServiceInterface:
    class: OxidEsales\OxidEshopUpdateComponent\Module\Service\ModuleSettingsTransferringService

  OxidEsales\OxidEshopUpdateComponent\Module\Service\ActiveModuleStateTransferringServiceInterface:
    class: OxidEsales\OxidEshopUpdateComponent\Module\Service\ActiveModuleStateTransferringService

  oxid_esales.oxid_eshop_update_component.service.module_extension_transferring_service:
    class: OxidEsales\OxidEshopUpdateComponent\Module\Service\ModuleExtensionsSortingService

  oxid_esales.oxid_eshop_update_component.service.module_extensions_sorting.extensions_sorter:
    class: OxidEsales\OxidEshopUpdateComponent\Module\Service\ModuleExtensionsSorting\ExtensionsSorter

  oxid_esales.oxid_eshop_update_component.adapter.shop_adapter:
    class: OxidEsales\OxidEshopUpdateComponent\Adapter\ShopAdapter
