services:
  _defaults:
    autowire: true

  OxidEsales\OxidEshopUpdateComponent\ThemeSettings\Transformer\ConfigValueDecoderInterface:
    class: OxidEsales\OxidEshopUpdateComponent\ThemeSettings\Transformer\ConfigValueDecoder

  OxidEsales\OxidEshopUpdateComponent\ThemeSettings\Fetcher\ThemeConfigurationFetcherInterface:
    class: OxidEsales\OxidEshopUpdateComponent\ThemeSettings\Fetcher\ThemeConfigurationFetcher

  OxidEsales\OxidEshopUpdateComponent\ThemeSettings\Migration\ThemeSettingsMigratorInterface:
    class: OxidEsales\OxidEshopUpdateComponent\ThemeSettings\Migration\ThemeSettingsMigrator

  OxidEsales\OxidEshopUpdateComponent\ThemeSettings\Remover\ThemeConfigurationRemoverInterface:
    class: OxidEsales\OxidEshopUpdateComponent\ThemeSettings\Remover\ThemeConfigurationRemover
